const onePieceCharacters = [
  'Monkey D. Luffy',
  'Roronoa Zoro',
  'Nami',
  'Usopp',
  'Vinsmoke Sanji',
  'Tony Tony Chopper',
  'Nico Robin',
  'Franky',
  'Brook',
  'Jimbei',
  'Shanks',
  'Dracule Mihawk',
  'Boa Hancock',
  'Buggy',
  'Edward Newgate (Whitebeard)',
  'Portgas D. Ace',
  'Trafalgar D. Water Law',
  'Donquixote Doflamingo',
  'Eustass Kid',
  'Kaido',
  'Big Mom',
  'Blackbeard',
  'Charlotte Katakuri',
  'Marco',
  'Jinbe',
  'Rob Lucci',
  'Sabo',
  'Crocodile',
  'Nico Robin',
  'Enel',
  'Kuzan (Aokiji)',
  'Fujitora (Issho)',
  'Kizaru (Borsalino)',
  'Akainu (Sakazuki)',
  'Smoker',
  'Tashigi'
]

module.exports = onePieceCharacters
