const onePieceCharacters = [
  'Monkey D. Luffy',
  'Roronoa Zoro',
  'Nami',
  'Usopp',
  'Vinsmoke Sanji',
  'Tony Tony Chopper',
  'Nico Robin',
  'Franky',
  'Brook',
  'Jimbei',
  'Shanks',
  'Dracule Mihawk',
  'Boa Hancock',
  'Buggy',
  'Edward Newgate',
  'Portgas D. Ace',
  'Law',
  'Doflamingo',
  'Eustass Kid',
  'Kaido',
  'Big Mom',
  'Blackbeard',
  'Katakuri',
  'Marco',
  'Jinbe',
  'Rob Lucci',
  'Sabo',
  'Crocodile',
  'Nico Robin',
  'Enel',
  'Kuzan (Aokiji)',
  'Fujitora (Issho)',
  'Borsalino',
  'Akainu (Sakazuki)',
  'Smoker',
  'Tashigi'
]

module.exports = onePieceCharacters
